In [94]:
import pandas as pd
import numpy as np
from path import Path
import matplotlib.pyplot as plt

In [95]:
# import file_path and make dataframe

quality_file_path = Path('./data/merged_data_cleaned.csv')
quality_df = pd.read_csv(quality_file_path, index_col=0)
quality_df.head()

,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,Region,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,NaN,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,oromia,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [110]:
# define clean columns function to make column_names_list

def clean_columns(df):
    column_names_list = []

    for col in df.columns: 
        col = col.replace('.','_')
        column_names_list.append(col)
    
    return column_names_list

In [112]:
# set column_names by calling clean_columns function
clean_column_names = clean_columns(quality_df)

# rename dataframe columns to clean_columns_list
quality_df.columns = clean_column_names

# rename Country_of_Origin column to Country_Name for sake of continuity
quality_df = quality_df.rename(columns={'Country_of_Origin':'Country_Name'})

print(clean_column_names)
print(quality_df.columns)

['Species', 'Owner', 'Country_Name', 'Farm_Name', 'Lot_Number', 'Mill', 'ICO_Number', 'Company', 'Altitude', 'Region', 'Producer', 'Number_of_Bags', 'Bag_Weight', 'In_Country_Partner', 'Harvest_Year', 'Grading_Date', 'Owner_1', 'Variety', 'Processing_Method', 'Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity', 'Clean_Cup', 'Sweetness', 'Cupper_Points', 'Total_Cup_Points', 'Moisture', 'Category_One_Defects', 'Quakers', 'Color', 'Category_Two_Defects', 'Expiration', 'Certification_Body', 'Certification_Address', 'Certification_Contact', 'unit_of_measurement', 'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters']
Index(['Species', 'Owner', 'Country_Name', 'Farm_Name', 'Lot_Number', 'Mill',
       'ICO_Number', 'Company', 'Altitude', 'Region', 'Producer',
       'Number_of_Bags', 'Bag_Weight', 'In_Country_Partner', 'Harvest_Year',
       'Grading_Date', 'Owner_1', 'Variety', 'Processing_Method', 'Aroma',
       'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity',
       'Clean_Cup', 'Sweetness', 'Cupper_Points', 'Total_Cup_Points',
       'Moisture', 'Category_One_Defects', 'Quakers', 'Color',
       'Category_Two_Defects', 'Expiration', 'Certification_Body',
       'Certification_Address', 'Certification_Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [98]:
# check null values
quality_df.isna().sum()

Species                     0
Owner                       7
Country_Name                1
Farm_Name                 359
Lot_Number               1063
Mill                      318
ICO_Number                157
Company                   209
Altitude                  226
Region                     59
Producer                  232
Number_of_Bags              0
Bag_Weight                  0
In_Country_Partner          0
Harvest_Year               47
Grading_Date                0
Owner_1                     7
Variety                   226
Processing_Method         170
Aroma                       0
Flavor                      0
Aftertaste                  0
Acidity                     0
Body                        0
Balance                     0
Uniformity                  0
Clean_Cup                   0
Sweetness                   0
Cupper_Points               0
Total_Cup_Points            0
Moisture                    0
Category_One_Defects        0
Quakers                     1
Color                     218
Category_Two_Defects        0
Expiration                  0
Certification_Body          0
Certification_Address       0
Certification_Contact       0
unit_of_measurement         0
altitude_low_meters       230
altitude_high_meters      230
altitude_mean_meters      230
dtype: int64

In [99]:
# check duplicates
quality_df.duplicated().sum()

0

In [100]:
# drop null values, nothing changed
quality_df.dropna()
quality_df.isna().sum()

Species                     0
Owner                       7
Country_Name                1
Farm_Name                 359
Lot_Number               1063
Mill                      318
ICO_Number                157
Company                   209
Altitude                  226
Region                     59
Producer                  232
Number_of_Bags              0
Bag_Weight                  0
In_Country_Partner          0
Harvest_Year               47
Grading_Date                0
Owner_1                     7
Variety                   226
Processing_Method         170
Aroma                       0
Flavor                      0
Aftertaste                  0
Acidity                     0
Body                        0
Balance                     0
Uniformity                  0
Clean_Cup                   0
Sweetness                   0
Cupper_Points               0
Total_Cup_Points            0
Moisture                    0
Category_One_Defects        0
Quakers                     1
Color                     218
Category_Two_Defects        0
Expiration                  0
Certification_Body          0
Certification_Address       0
Certification_Contact       0
unit_of_measurement         0
altitude_low_meters       230
altitude_high_meters      230
altitude_mean_meters      230
dtype: int64

In [113]:
quality_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1339 entries, 0 to 1338
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Species                1339 non-null   object
 1   Owner                  1332 non-null   object
 2   Country_Name           1338 non-null   object
 3   Farm_Name              980 non-null    object
 4   Lot_Number             276 non-null    object
 5   Mill                   1021 non-null   object
 6   ICO_Number             1182 non-null   object
 7   Company                1130 non-null   object
 8   Altitude               1113 non-null   object
 9   Region                 1280 non-null   object
 10  Producer               1107 non-null   object
 11  Number_of_Bags         1339 non-null   int64
 12  Bag_Weight             1339 non-null   object
 13  In_Country_Partner     1339 non-null   object
 14  Harvest_Year           1292 non-null   object
 15  Grading_Date           1339 non-null   object
 16  Owner_1                1332 non-null   object
 17  Variety                1113 non-null   object
 18  Processing_Method      1169 non-null   object
 19  Aroma                  1339 non-null   float64
 20  Flavor                 1339 non-null   float64
 21  Aftertaste             1339 non-null   float64
 22  Acidity                1339 non-null   float64
 23  Body                   1339 non-null   float64
 24  Balance                1339 non-null   float64
 25  Uniformity             1339 non-null   float64
 26  Clean_Cup              1339 non-null   float64
 27  Sweetness              1339 non-null   float64
 28  Cupper_Points          1339 non-null   float64
 29  Total_Cup_Points       1339 non-null   float64
 30  Moisture               1339 non-null   float64
 31  Category_One_Defects   1339 non-null   int64
 32  Quakers                1338 non-null   float64
 33  Color                  1121 non-null   object
 34  Category_Two_Defects   1339 non-null   int64
 35  Expiration             1339 non-null   object
 36  Certification_Body     1339 non-null   object
 37  Certification_Address  1339 non-null   object
 38  Certification_Contact  1339 non-null   object
 39  unit_of_measurement    1339 non-null   object
 40  altitude_low_meters    1109 non-null   float64
 41  altitude_high_meters   1109 non-null   float64
 42  altitude_mean_meters   1109 non-null   float64
dtypes: float64(16), int64(3), object(24)
memory usage: 460.3+ KB

In [115]:
# checking to see how many rows have 0 null values
quality_df_small = quality_df.dropna(how='any')
quality_df_small.info()

# only 132 out of 1339 total

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132 entries, 29 to 1322
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Species                132 non-null    object
 1   Owner                  132 non-null    object
 2   Country_Name           132 non-null    object
 3   Farm_Name              132 non-null    object
 4   Lot_Number             132 non-null    object
 5   Mill                   132 non-null    object
 6   ICO_Number             132 non-null    object
 7   Company                132 non-null    object
 8   Altitude               132 non-null    object
 9   Region                 132 non-null    object
 10  Producer               132 non-null    object
 11  Number_of_Bags         132 non-null    int64
 12  Bag_Weight             132 non-null    object
 13  In_Country_Partner     132 non-null    object
 14  Harvest_Year           132 non-null    object
 15  Grading_Date           132 non-null    object
 16  Owner_1                132 non-null    object
 17  Variety                132 non-null    object
 18  Processing_Method      132 non-null    object
 19  Aroma                  132 non-null    float64
 20  Flavor                 132 non-null    float64
 21  Aftertaste             132 non-null    float64
 22  Acidity                132 non-null    float64
 23  Body                   132 non-null    float64
 24  Balance                132 non-null    float64
 25  Uniformity             132 non-null    float64
 26  Clean_Cup              132 non-null    float64
 27  Sweetness              132 non-null    float64
 28  Cupper_Points          132 non-null    float64
 29  Total_Cup_Points       132 non-null    float64
 30  Moisture               132 non-null    float64
 31  Category_One_Defects   132 non-null    int64
 32  Quakers                132 non-null    float64
 33  Color                  132 non-null    object
 34  Category_Two_Defects   132 non-null    int64
 35  Expiration             132 non-null    object
 36  Certification_Body     132 non-null    object
 37  Certification_Address  132 non-null    object
 38  Certification_Contact  132 non-null    object
 39  unit_of_measurement    132 non-null    object
 40  altitude_low_meters    132 non-null    float64
 41  altitude_high_meters   132 non-null    float64
 42  altitude_mean_meters   132 non-null    float64
dtypes: float64(16), int64(3), object(24)
memory usage: 45.4+ KB

In [117]:
# define get_unique_values_df function to make a dataframe of each column and its unique values

def get_unique_values_df(df):
    # initialize unique_dict and unique_values_list
    unique_dict = {}
    unique_values_list = []

    # copy dataframe
    df = df.copy()

    # iterate through columns
    for column in df.columns:
        # extract unique values
        unique_values = df[column].unique()
        # append unique values from each column to unique_values_list
        unique_values_list.append(unique_values)

    # make a dataframe of column name and unique values 
    values_df = pd.DataFrame({'Column Name':[col for col in df.columns], 'Unique_Values': unique_values_list}) 

    # return dataframe
    return values_df

In [118]:
unique_values_df = get_unique_values_df(quality_df)
unique_values_df.head(10)

    Column Name                                      Unique_Values
0       Species                                 [Arabica, Robusta]
1         Owner  [metad plc, grounds for health admin, yidnekac...
2  Country_Name  [Ethiopia, Guatemala, Brazil, Peru, United Sta...
3     Farm_Name  [metad plc, san marcos barrancas "san cristoba...
4    Lot_Number  [nan, YNC-06114, 102, Tsoustructive 2015 Sumat...
5          Mill  [metad plc, nan, wolensu, hvc, c.p.w.e, tulla ...
6    ICO_Number  [2014/2015, nan, 010/0338, 2014/15, unknown, 0...
7       Company  [metad agricultural developmet plc, nan, yidne...
8      Altitude  [1950-2200, 1600 - 1800 m, 1800-2200, nan, 157...
9        Region  [guji-hambela, nan, oromia, oromiya, snnp/kaff...

In [124]:
# define function to get unique values from input column
def get_unique_values(member):
    # extract unique values from input column
    unique_values = member.unique()
    # print the number of unique values
    print(len(unique_values))
    # print unique values
    print(unique_values)

    # return unique values
    return unique_values

In [131]:
country_values = get_unique_values(quality_df['Country_Name'])

37
['Ethiopia' 'Guatemala' 'Brazil' 'Peru' 'United States'
 'United States (Hawaii)' 'Indonesia' 'China' 'Costa Rica' 'Mexico'
 'Uganda' 'Honduras' 'Taiwan' 'Nicaragua' 'Tanzania, United Republic Of'
 'Kenya' 'Thailand' 'Colombia' 'Panama' 'Papua New Guinea' 'El Salvador'
 'Japan' 'Ecuador' 'United States (Puerto Rico)' 'Haiti' 'Burundi'
 'Vietnam' 'Philippines' 'Rwanda' 'Malawi' 'Laos' 'Zambia' 'Myanmar'
 'Mauritius' 'Cote d?Ivoire' nan 'India']

In [130]:
company_values = get_unique_values(quality_df['Company'])

282
['metad agricultural developmet plc' nan
 'yidnekachew debessa coffee plantation'
 'richmond investment-coffee department' 'diamond enterprise plc'
 'fahem coffee plantation' 'coffee quality institute'
 'yunnan coffee exchange' 'essence coffee' 'the coffee source inc.'
 'nucoffee' 'kabum trading company' 'cigrah s.a de c.v'
 'taiwan coffee laboratory' 'exclusive coffees s.a.'
 'haider abamecha coffee export' 'c dorman ltd'
 'kona pacific farmers cooperative' 'lanna cafe' 'keremara limited' 'ucda'
 'lusso coffee lab' 'kawacom uganda ltd' 'unex guatemala, s.a.'
 'exportadora de cafe condor s.a' 'ce specialty s.a.'
 'ibrahim hussien specality coffee product & exporter' 'sertrasa'
 'unicafe' 'seid damtew coffee planation' 'sustainable harvest' 'cqi'
 'atlantic specialty coffee' 'assefa belay coffee producer'
 'kyagalanyi coffee ltd' 'exportcafe' 'great lakes coffee'
 'rashid moledina & co. (msa) ltd' 'ibero kenya limited' 'ecom cca sa'
 'nomura trading co., ltd.' 'carcafe ltda'
 'the specialty coffee appraisers institute of asia' 'racafe & cia s.c.a'
 'bold coast coffee'
 'cafetal el equimite, rancho agroecológico, s.p.r. de r.l.'
 'taylor winch (t) ltd' 'matsuzawa coffee' 'cadexsa'
 'cafetalera del pacifico' 'pt. shriya artha nusantara'
 'panamerican coffee trading'
 'waelti schoenfeld exportadores de cafe, s.a.' 'coopetarrazú.r.l'
 'coricafe s.a.' 'thrive farmers' 'blossom valley宸嶧國際'
 'dream together inc.'
 'organizaciones de productores de cafe colimense sa de cv' 'ugacof ltd'
 'armajaro guatemala, s. a.' 'taylor winch (coffee) ltd'
 'beneficios volcafé costa rica' 'federacion nacional de cafeteros'
 'puer jiangcheng fuwang coffee biotechnology co., ltd'
 'dream together co. ltd' 'ecomtrading' 'transcafe, s.a'
 'pt. olam indonesia' 'tropica galliard' 'finca hamburgo'
 'skn caribecafe ltda' 'siembras vision, s.a.' 'tembo coffee company ltd'
 'carajillo café sa de cv' 'bukonzo joint cfs'
 'exclusive coffee - costa rica' 'cafcom' 'cooperativa el gorrion r.l'
 'cafebras comercio de cafés do brasil sa' 'ceca,s.a.'
 'asefa dukamo coffee plantetion' 'selian coffee estate'
 'olam international ltd' 'volcafe specialty coffee' 'café do paraíso'
 'pt. royal pacific indah international' 'ipanema coffees'
 'mae fah luang foundation' 'cafes tomari sa de cv'
 'intercof 1978 group company limited' '宸嶧國際' 'agro xicotepec 2000'
 'yasmin coffee plantation plc' 'sultana del cafe inc.'
 'exportadora de cafés carmo de minas ltda'
 'nile highlands arabica coffee farmers' 'hacienda alto grande, llc.'
 'comercial internacional exportadora, s.a.'
 'doi tung development project' 'olam specialty coffee' 'scai'
 'exportadora café california' 'bulamburi coffee farmers association'
 'c.i.racafe & cia s.c.a' 'tawoca' 'debesa agro industry plc' 'cigrah'
 'finca los barreales' 'estrategias constructivas corzu s.a. de c.v.'
 'kanematsu corporation / rnp santo tomas pachuj' 'coffee resources inc.'
 'bugisu cooperative union' 'consejo salvadoreño del café'
 'bourbon specialty coffees' 'ngila estate ltd' 'mondul coffee estate'
 'café andrade, s.a. de c.v.' 'itiah coffee llc.'
 'cafe de don balbino s.c. de r.l. de c.v.' 'mercon guatemala s.a.'
 'productos y servicios chilindron s.a. de c.v.'
 'finca triunfo verde, s.c.' 'finca teocelo'
 'volcafe/taylorwinch tanzania ltd' 'prodlesur sa' 'sunvirtue co., ltd.'
 'tutunze kahawa ltd' 'green mountain coffee' 'olam honduras, s.a.'
 'agricola nueva granada, s.a.' 'cesmach s.c.' 'finca las nubes' 'ucfa'
 'atlantica eportacao e importcao ltda' 'star cafe ltd'
 'finca la estancia' 'nuevos mercados, s.a.'
 'soc. coop. cuzcachapa de r.l.' 'belayneh kindie' 'hineleban foundation'
 'ephemera traders' "tony's coffee and teas, inc." 'expocaccer'
 'nyapea coffee farmers association' 'royal base corporation'
 'union de ejidos san fernando de ri' 'bufcoffee ltd'
 'coffeebythebag.com , inc.' 'tcb' 'beneficio custepec s.a. de c.v.'
 'inmobiliaria e inversiones dos mil s.a.'
 'soc. coop. de caf. de ciudad barrios de r.l.'
 'mzuzu coffee planters coop union' 'coffee export' 'cafe shunuc'
 'ecom cca s.a.' 'hacienda la esmeralda' 'finca kassandra'
 'nitin coffee estate' 'afca' 'coffeas co., ltd' 'finca medina'
 'cafe montegrande' 'grupo cafetalero los brujos' 'volcafe ltda.'
 'pt. sari makmur tunggal mandiri' 's&d coffee and tea' 'shah plantations'
 'amkeni gourmet coffee group' 'cafe de la sierra norte de puebla'
 'finca santa cruz' 'carrillo cooperativa'
 'asociación nacional del café - anacafe -' 'finca las nieves' 'olam'
 'f. gaviña & sons, inc.' 'finca el morito' 'eczcafe fino s.a. de c.v.'
 'klem organics coffee' 'siembras vision, s.a. / ing. jorge bolaños'
 'beneficiadora norteña de cafe, s. a. (bencafe)' 'ibero tanzania'
 'red on tree co., ltd.' 'cafetalera internacional cafinter, s.a.'
 'ngorogoro convenant estate' 'cafe politico'
 'indigenas de la sierra madre de motozintla san isidro labrador s. de s.s.'
 'kettles coffee roasters' 'finca estate' 'beneficio santa rosa s.a.'
 'elfasa, s.a.' 'mcomafa co. ltd'
 'agroindustrias unidas de mexico sa de cv' 'globus coffee'
 'dae ltd company' 'union ramal santa cruz spr de ri'
 'productora agricola y ganadera finca la suiza, s.p.r. de r.l. de c.v.'
 'estrategias constructivas corzu, s.a. de c.v.' 'molinos de honduras'
 'acacia hills ltd' 'exportadora atlantic s.a'
 'aung nay lin htun co., ltd'
 'santa laura exportadora de cafe s.l.e.c. s.a.' 'outspan guatemala s.a.'
 'haiti coffee' 'ac la laja sa de cv' 's3v international importing'
 'shangrilla estate ltd' 'mviwambi coffee farm' 'r.w.j wallace ltd'
 'kerchanshe trading plc' 'garca armazens' 'conscious bean coffee'
 'cafetera el grande s.a. de c.v.'
 'comercializadora profesional mexicana s.a. de c.v.' 'kpfc'
 'mlimani ngarashi' 'industrializadora de kaffee andes s.a. de c.v.'
 '八杞莊園' 'grupo santab s.a. de c.v.' 'sithar coffee co., ltd.'
 'karatu estate' 'productora rural la victoria s.p.r. de r.l.'
 'café san blas' 'cafe don balbino s.c. de r.l. de c.v.'
 'finca santo tomas pachuj, guatemala' 'burka coffee estate' '王秋金'
 'peter schoelfeld, s.a' 'coffee planet corporation s.a'
 'compagnie sucrière de bel ombre ltd' 'shwe yin mar coffee'
 'cafeorganico.mx' 'yunnan new century tech inc.'
 'sangana commodities k limited' 'delfina farm' 'kongoni estate'
 'waylead industrial co, ltd.' 'zeas escobar y compañía limitada'
 'costco wholesale industries' 'café katsina'
 'cafes de naranjal s.a. de c.v' 'carmo coffees'
 'ngu shwe li coffee estate' 'cafetalera la asunción s.a. de c.v.'
 'asociación aldea global jinotega' 'comon yaj noptic s. de ss'
 'cafessisimo compañia s.a. de c.v.' 'royal 1750 coffee'
 'productores e industrializadores de café orgánico la fe s.c. de r.l.'
 'cafes finos de exportacion s de r.l.' 'café monteabuelo s.a. de c.v.'
 'café pico de loro' 'empagri s.p.r. de r.l. de c.v.'
 'yunnan louis herbs r& d center' 'unión de ejidos san fernando'
 'villa talea café'
 'asociación agricola local de productores de café de huautla de jimenez        '
 'greenhouse coffee china' 'olam japan' 'exportadora moretto s.a. de c.v.'
 'eduardo ambrocio' 'el mejor café' 'prime3' 'sposel s. de s.s.'
 'union regional de cafeticultores de la mazateca alta'
 'grupo juvenil magtayani ac' 'upctiz zapoteca s.p.r. de r.l.'
 'cafe colonial de tlatlauquitepec' 'terra mia'
 'ankole coffee producers coop' 'kaapi royale' 'sethuraman estate'
 'katuka development trust ltd' 'cafemakers, llc' 'cafemakers'
 'kasozi coffee farmers association' 'nitubaasa ltd'
 'mannya coffee project' 'robustasa' 'global opportunity fund']

In [127]:
region_values = get_unique_values(quality_df['Region'])

357
['guji-hambela' nan 'oromia' 'oromiya' 'snnp/kaffa zone,gimbowereda'
 'antioquia' 'kona' 'sulawesi' 'yirgacheffe' 'yunnan' 'gedio' 'san ramon'
 'xalapa' 'sidamo' 'south of minas' 'kapchorwa eastern' 'comayagua'
 'leye, alishan township, chiayi county' 'vale da grama'
 'west and central valley' 'muranga' 'chiang rai'
 'sul de minas - carmo de minas' 'natou county' 'nyeri' 'eastern uganda'
 'tolima' 'kiambu' 'sipi, mt elgon' 'nuevo oriente' 'eastern' 'huila'
 'boquete' 'acatenango' 'addis ababa' 'cajamarca'
 'eastern highlands province' 'apaneca'
 'ataco, apaneca - ilamatepec mountain range' 'kirinyaga'
 'bulambuli eastern region' 'huehuetenango' 'kapchorwa' 'west valley'
 'central kenya' 'oriente' 'santander' 'lintong'
 'kefa zone, gimbo distict, at a place called woka araba, south west ethiopia.'
 'pasto' 'aricha' 'cundinamarca' 'tarrazu' 'veracruz' 'grama valley'
 'mexico' 'chuva, san marcos' 'mbeya' 'coatepec'
 'dongshan dist., tainan city 臺南市東山區' 'thailand' 'marcala' 'santa ana'
 'jinotega' 'temanggung, indonesia' 'ada okinawa japan' 'costa rica'
 'taichung xinshe 台中市新社區' 'el remudadero' 'mbale' 'penachi, cecanor'
 'jalapa' 'tres rios' 'mountains of minas gerais' 'valle central' 'cauca'
 'hustusco' 'jaltenango' 'el tumbador, san marcos' 'mmm' 'test'
 'sumatra brastagi' 'pitalito' 'mountain ali, taiwan' 'tapachula' 'limu'
 'central region' 'la plata' 'tuxtla gutierrez' '國姓鄉 guoshing township'
 'chiang rai thailand' 'nariño' 'antigua' 'shizingo village'
 'san pedro cotzilnam' 'la concordia, chiapas' 'kasese' 'san marcos'
 'solola' 'norte' 'cerrado' 'snnprg; kafa; telo woreda; shada kebele'
 'arusha' 'kenya' 'minas gerais, br' 'guatemala' 'mt. rwenzori'
 'aceh tengah' 'nanxi dist., tainan city 臺南市楠西區'
 'aldea xeucalvitz, ixil region, quiche department'
 'santo domingo cacalotepec' 'ethiopia, sidamo' 'blend' 'chiangrai'
 'leye, alishan township, chiayi county 嘉義阿里山樂野村' '台灣' '台中和平區'
 'xicotepec de juarez' 'la concordia' 'la yerbabuena' 'central valley'
 'province of manabi, ecuador' 'petatlan' 'carmo de minas'
 'doi chaang village, chiang rai, thialand'
 '台南市東山區 (dongshan dist., tainan city)' 'west nile' 'yauco region'
 'huazalingo, hidalgo' 'quetzaltenango' 'meru county' 'huila supremo'
 'east java' 'sacatepequez, guatemala' 'chiapas, jaltenango' 'nkure- meru'
 'bener meriah' 'atitlan' 'chilón' 'totutla' 'bondowoso' 'karatu northern'
 'nayarit' 'guayata' 'chiapas' 'thiotte, haiti' 'kayanza'
 'sierra madre occidental' 'campos altos - cerrado' 'cuarenteño' '南投國姓'
 'eje cafetero' 'fortín de las flores' 'moshi' 'dala' 'dehong prefecture'
 'mbinga' 'kilimanjaro' 'tlanchinol, hidalgo' 'san bartolo tutotepec'
 'san isidro' 'mogiana' 'chapadão de ferro (cerrado mineiro)'
 'chiayi alishan 嘉義縣阿里山鄉' 'santa catarina juquila' 'dolok sanggul'
 'kasese, mt. rwenzori' 'vietnam cau dat' 'high mogiana' '嘉義阿里山'
 'sul de minas' 'atoyac de alvarez' 'la reforma, san marcos' 'matagalpa'
 'blida,kercha,guji,oromia' '台東太麻里' 'bukidnon, mindanao, philppines'
 'asia pacific' 'don duong' 'la cumbre' 'el balsamo, quezaltepec'
 'gicumbi' 'vietnam tutra' 'berastagi' 'santa rosa' 'sapan toraja'
 'el progreso' '台南市東山區( dongshan dist., tainan city)' 'cacahuatique'
 'menglian' 'mzuzu' 'south huila' 'paksong,laos' 'monte carmelo'
 'karatu arusha' 'la yerba' 'mt elgon' 'phahi' 'mahuixtlan'
 '52 narino (exact location: mattituy; municipal region: florida code 381'
 'changhua baguashan 彰化市八卦山' 'aceh' 'ikand village' 'oaxaca' 'colima'
 'bali' 'zapotitlan de mendez' 'comayagua, honduras' 'arusha meru' 'peru'
 'zihuatanejo de azueta' 'progreso santa rosa teocelo' 'fln mirador'
 'xishuangbanna prefecture' 'jaltocan, hidalgo' 'brazil matas de minas'
 'nantou' 'calnali, hidalgo' 'juquila' 'canoas' 'ruvuma' 'northern'
 'ilomba vilage, mbozi' 'yunlin 雲林縣石壁' 'altotonga' 'aceh gayo' 'ngorogoro'
 'turrialba' 'el paraíso' 'guinope el paraíso' 'lao p.d.r.' 'meru'
 'occidental' 'coscomatepec' 'mubuyu estate' 'chapulhuacan, hidalgo'
 'ywar ngan' 'lington nihuta' 'kakoma'
 'siltepec el triunfo, chiapas, mexico' 'vietnam'
 'tenango de doria, hidalgo' 'tepictla' 'yajalon'
 'sacún palma, municipio de chilón, chiapas' 'western region'
 'oldeani , mongola' '古坑鄉荷包村尖山坑60號' 'ywar ngan township' 'dondon, haiti'
 'amatenango de la frontera' 'temaxcalapa' 'manzanillo' 'ijen' '苗栗三灣'
 'san lucas toliman, solola' 'siltepec el triunfo' 'puno'
 'coatepec, coatepec' 'mantiqueira de minas' 'davao city, region 11'
 'matas de minas        ' 'dongshan dist., tainan city 台南市東山區'
 'karatu ngorogoro' 'motozintla' 'dipilto, nueva segovia' 'ruvuma, mbinga'
 'corillera administrative' 'southern- zomba' 'alta paulista (sao paulo)'
 'central america' 'iwala village, mbeya rural' 'naranjo' 'san fernando'
 'santo reyes nopala' 'santa maria sitepec' 'talpa de allende'
 'motozintla, chiapas' 'adolfo lopez mateos' 'taiwan' 'pyinoolwin'
 'manyara, karatu' '台中新社' 'taichung taiping 台中市太平區'
 'new taipei zhonghe 新北市中和區' 'ixhuatlan del cafe' 'orient'
 'siguatepeque, comayagua' 'haiti'
 'el desmoronado, talpan de allende jalisco' 'nueva segovia' 'ocotepeque'
 'chamarel (south west)' 'pyin oo lwin' 'zaragoza itundujia'
 'department of ahuachapan, municipality of apanecallamatepec mountain'
 'pochutla' 'mumirwa' 'mkuu rombo' 'kelem welega'
 'cerrado - monte carmelo - minas gerais' 'yauk sauk, shan state'
 'chiayi fanlu嘉義縣番路鄉' '苗栗泰安' 'yunlin gukeng he bao 雲林縣古坑鄉荷苞村' 'escuitla'
 'doe kwin, pyin oo lwin' 'sierra fraylesca, chiapas'
 'san miguel del puerto' 'taiwu township , pingtung county 屏東縣泰武鄉'
 'baihe dist., tainan city 臺南市白河區' 'huanuco' 'brunca' 'tepetzingo'
 'cnra station of divo' 'pereira' 'zentla' 'occidente' 'san rafael'
 'pluma hidalogo, oaxaca' 'tlacuilotepec' 'intibuca' 'san ignacio'
 'iliatenco, guerrero' 'ohuapan, tlaltetela' 'yecuatla'
 'cofradia de suchitlan' 'sierra, chiapas' 'villa talea de castro'
 'los angeles' 'xochitonalco, huautla        ' 'cordoba' 'chickmangalore'
 'indonesia' 'benguet, mountain province' 'ocosingo' 'huautla de jimenez'
 'chocaman, veracruz' 'sierra alta mixe y zapoteca' 'marmelade'
 'tlatlauquitepec' 'sierra norte yajalon, chiapas' 'juchique de ferrer'
 "department d'artibonite , haiti" 'sheema south western'
 'chikmagalur karnataka indua' 'chikmagalur' 'central'
 'luwero central region' 'chikmagalur karnataka india'
 'chikmagalur karnataka' 'western' 'iganga namadrope eastern'
 'south western' 'southern' 'san juan, playas'
 'kwanza norte province, angola']

In [129]:
species_values = get_unique_values(quality_df['Species'])

2
['Arabica' 'Robusta']